server:
  port: 8096

user:
  userServiceUrl: http://localhost:8080/findUser?id=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: consumer-movie