server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: file-upload
  http:
    multipart:
      max-file-size: 2000Mb
      max-request-size: 2500Mb