server:
  port: 8090

user:
  userServiceUrl: http://localhost:8080/user?id=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: consumer-movie