spring:
  application:
    name: registry-ha

---

spring:
  profiles: peer1

server:
  port: 9001

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:9002/eureka/

---

spring:
  profiles: peer2

server:
  port: 9002

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/