server:
  port: 8102

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: consumer-movie

ribbon:
  ConnectTimeout: 300